// Code generated by ent, DO NOT EDIT.

package warehouse

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the warehouse type in the database.
	Label = "warehouse"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldAddressLine holds the string denoting the address_line field in the database.
	FieldAddressLine = "address_line"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldLongtitude holds the string denoting the longtitude field in the database.
	FieldLongtitude = "longtitude"
	// EdgeWarehouseOrder holds the string denoting the warehouse_order edge name in mutations.
	EdgeWarehouseOrder = "warehouse_order"
	// Table holds the table name of the warehouse in the database.
	Table = "warehouses"
	// WarehouseOrderTable is the table that holds the warehouse_order relation/edge.
	WarehouseOrderTable = "orders"
	// WarehouseOrderInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	WarehouseOrderInverseTable = "orders"
	// WarehouseOrderColumn is the table column denoting the warehouse_order relation/edge.
	WarehouseOrderColumn = "warehouse_warehouse_order"
)

// Columns holds all SQL columns for warehouse fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldAddressLine,
	FieldLatitude,
	FieldLongtitude,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
