// Code generated by ent, DO NOT EDIT.

package drone

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the drone type in the database.
	Label = "drone"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldLongtitude holds the string denoting the longtitude field in the database.
	FieldLongtitude = "longtitude"
	// FieldInWarehouse holds the string denoting the in_warehouse field in the database.
	FieldInWarehouse = "in_warehouse"
	// FieldPlateNumber holds the string denoting the plate_number field in the database.
	FieldPlateNumber = "plate_number"
	// EdgeCurrentOrder holds the string denoting the current_order edge name in mutations.
	EdgeCurrentOrder = "current_order"
	// Table holds the table name of the drone in the database.
	Table = "drones"
	// CurrentOrderTable is the table that holds the current_order relation/edge.
	CurrentOrderTable = "orders"
	// CurrentOrderInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	CurrentOrderInverseTable = "orders"
	// CurrentOrderColumn is the table column denoting the current_order relation/edge.
	CurrentOrderColumn = "drone_current_order"
)

// Columns holds all SQL columns for drone fields.
var Columns = []string{
	FieldID,
	FieldLatitude,
	FieldLongtitude,
	FieldInWarehouse,
	FieldPlateNumber,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultInWarehouse holds the default value on creation for the "in_warehouse" field.
	DefaultInWarehouse bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
