// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TheOguzhan/Drone-Mobile-App-Backend/ent/address"
	"github.com/TheOguzhan/Drone-Mobile-App-Backend/ent/order"
	"github.com/TheOguzhan/Drone-Mobile-App-Backend/ent/predicate"
	"github.com/TheOguzhan/Drone-Mobile-App-Backend/ent/user"
	"github.com/google/uuid"
)

// AddressUpdate is the builder for updating Address entities.
type AddressUpdate struct {
	config
	hooks    []Hook
	mutation *AddressMutation
}

// Where appends a list predicates to the AddressUpdate builder.
func (au *AddressUpdate) Where(ps ...predicate.Address) *AddressUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetName sets the "name" field.
func (au *AddressUpdate) SetName(s string) *AddressUpdate {
	au.mutation.SetName(s)
	return au
}

// SetAddressLine sets the "address_line" field.
func (au *AddressUpdate) SetAddressLine(s string) *AddressUpdate {
	au.mutation.SetAddressLine(s)
	return au
}

// SetLatitude sets the "latitude" field.
func (au *AddressUpdate) SetLatitude(f float64) *AddressUpdate {
	au.mutation.ResetLatitude()
	au.mutation.SetLatitude(f)
	return au
}

// AddLatitude adds f to the "latitude" field.
func (au *AddressUpdate) AddLatitude(f float64) *AddressUpdate {
	au.mutation.AddLatitude(f)
	return au
}

// SetLongtitude sets the "longtitude" field.
func (au *AddressUpdate) SetLongtitude(f float64) *AddressUpdate {
	au.mutation.ResetLongtitude()
	au.mutation.SetLongtitude(f)
	return au
}

// AddLongtitude adds f to the "longtitude" field.
func (au *AddressUpdate) AddLongtitude(f float64) *AddressUpdate {
	au.mutation.AddLongtitude(f)
	return au
}

// SetDescription sets the "description" field.
func (au *AddressUpdate) SetDescription(s string) *AddressUpdate {
	au.mutation.SetDescription(s)
	return au
}

// SetAddressOwnerID sets the "address_owner" edge to the User entity by ID.
func (au *AddressUpdate) SetAddressOwnerID(id uuid.UUID) *AddressUpdate {
	au.mutation.SetAddressOwnerID(id)
	return au
}

// SetAddressOwner sets the "address_owner" edge to the User entity.
func (au *AddressUpdate) SetAddressOwner(u *User) *AddressUpdate {
	return au.SetAddressOwnerID(u.ID)
}

// SetAddressOrderID sets the "address_order" edge to the Order entity by ID.
func (au *AddressUpdate) SetAddressOrderID(id uuid.UUID) *AddressUpdate {
	au.mutation.SetAddressOrderID(id)
	return au
}

// SetNillableAddressOrderID sets the "address_order" edge to the Order entity by ID if the given value is not nil.
func (au *AddressUpdate) SetNillableAddressOrderID(id *uuid.UUID) *AddressUpdate {
	if id != nil {
		au = au.SetAddressOrderID(*id)
	}
	return au
}

// SetAddressOrder sets the "address_order" edge to the Order entity.
func (au *AddressUpdate) SetAddressOrder(o *Order) *AddressUpdate {
	return au.SetAddressOrderID(o.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (au *AddressUpdate) Mutation() *AddressMutation {
	return au.mutation
}

// ClearAddressOwner clears the "address_owner" edge to the User entity.
func (au *AddressUpdate) ClearAddressOwner() *AddressUpdate {
	au.mutation.ClearAddressOwner()
	return au
}

// ClearAddressOrder clears the "address_order" edge to the Order entity.
func (au *AddressUpdate) ClearAddressOrder() *AddressUpdate {
	au.mutation.ClearAddressOrder()
	return au
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AddressUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, AddressMutation](ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AddressUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AddressUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AddressUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AddressUpdate) check() error {
	if _, ok := au.mutation.AddressOwnerID(); au.mutation.AddressOwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Address.address_owner"`)
	}
	return nil
}

func (au *AddressUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(address.FieldName, field.TypeString, value)
	}
	if value, ok := au.mutation.AddressLine(); ok {
		_spec.SetField(address.FieldAddressLine, field.TypeString, value)
	}
	if value, ok := au.mutation.Latitude(); ok {
		_spec.SetField(address.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := au.mutation.AddedLatitude(); ok {
		_spec.AddField(address.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := au.mutation.Longtitude(); ok {
		_spec.SetField(address.FieldLongtitude, field.TypeFloat64, value)
	}
	if value, ok := au.mutation.AddedLongtitude(); ok {
		_spec.AddField(address.FieldLongtitude, field.TypeFloat64, value)
	}
	if value, ok := au.mutation.Description(); ok {
		_spec.SetField(address.FieldDescription, field.TypeString, value)
	}
	if au.mutation.AddressOwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.AddressOwnerTable,
			Columns: []string{address.AddressOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.AddressOwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.AddressOwnerTable,
			Columns: []string{address.AddressOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.AddressOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   address.AddressOrderTable,
			Columns: []string{address.AddressOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: order.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.AddressOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   address.AddressOrderTable,
			Columns: []string{address.AddressOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: order.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AddressUpdateOne is the builder for updating a single Address entity.
type AddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AddressMutation
}

// SetName sets the "name" field.
func (auo *AddressUpdateOne) SetName(s string) *AddressUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetAddressLine sets the "address_line" field.
func (auo *AddressUpdateOne) SetAddressLine(s string) *AddressUpdateOne {
	auo.mutation.SetAddressLine(s)
	return auo
}

// SetLatitude sets the "latitude" field.
func (auo *AddressUpdateOne) SetLatitude(f float64) *AddressUpdateOne {
	auo.mutation.ResetLatitude()
	auo.mutation.SetLatitude(f)
	return auo
}

// AddLatitude adds f to the "latitude" field.
func (auo *AddressUpdateOne) AddLatitude(f float64) *AddressUpdateOne {
	auo.mutation.AddLatitude(f)
	return auo
}

// SetLongtitude sets the "longtitude" field.
func (auo *AddressUpdateOne) SetLongtitude(f float64) *AddressUpdateOne {
	auo.mutation.ResetLongtitude()
	auo.mutation.SetLongtitude(f)
	return auo
}

// AddLongtitude adds f to the "longtitude" field.
func (auo *AddressUpdateOne) AddLongtitude(f float64) *AddressUpdateOne {
	auo.mutation.AddLongtitude(f)
	return auo
}

// SetDescription sets the "description" field.
func (auo *AddressUpdateOne) SetDescription(s string) *AddressUpdateOne {
	auo.mutation.SetDescription(s)
	return auo
}

// SetAddressOwnerID sets the "address_owner" edge to the User entity by ID.
func (auo *AddressUpdateOne) SetAddressOwnerID(id uuid.UUID) *AddressUpdateOne {
	auo.mutation.SetAddressOwnerID(id)
	return auo
}

// SetAddressOwner sets the "address_owner" edge to the User entity.
func (auo *AddressUpdateOne) SetAddressOwner(u *User) *AddressUpdateOne {
	return auo.SetAddressOwnerID(u.ID)
}

// SetAddressOrderID sets the "address_order" edge to the Order entity by ID.
func (auo *AddressUpdateOne) SetAddressOrderID(id uuid.UUID) *AddressUpdateOne {
	auo.mutation.SetAddressOrderID(id)
	return auo
}

// SetNillableAddressOrderID sets the "address_order" edge to the Order entity by ID if the given value is not nil.
func (auo *AddressUpdateOne) SetNillableAddressOrderID(id *uuid.UUID) *AddressUpdateOne {
	if id != nil {
		auo = auo.SetAddressOrderID(*id)
	}
	return auo
}

// SetAddressOrder sets the "address_order" edge to the Order entity.
func (auo *AddressUpdateOne) SetAddressOrder(o *Order) *AddressUpdateOne {
	return auo.SetAddressOrderID(o.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (auo *AddressUpdateOne) Mutation() *AddressMutation {
	return auo.mutation
}

// ClearAddressOwner clears the "address_owner" edge to the User entity.
func (auo *AddressUpdateOne) ClearAddressOwner() *AddressUpdateOne {
	auo.mutation.ClearAddressOwner()
	return auo
}

// ClearAddressOrder clears the "address_order" edge to the Order entity.
func (auo *AddressUpdateOne) ClearAddressOrder() *AddressUpdateOne {
	auo.mutation.ClearAddressOrder()
	return auo
}

// Where appends a list predicates to the AddressUpdate builder.
func (auo *AddressUpdateOne) Where(ps ...predicate.Address) *AddressUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AddressUpdateOne) Select(field string, fields ...string) *AddressUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Address entity.
func (auo *AddressUpdateOne) Save(ctx context.Context) (*Address, error) {
	return withHooks[*Address, AddressMutation](ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AddressUpdateOne) SaveX(ctx context.Context) *Address {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AddressUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AddressUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AddressUpdateOne) check() error {
	if _, ok := auo.mutation.AddressOwnerID(); auo.mutation.AddressOwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Address.address_owner"`)
	}
	return nil
}

func (auo *AddressUpdateOne) sqlSave(ctx context.Context) (_node *Address, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Address.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, address.FieldID)
		for _, f := range fields {
			if !address.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != address.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(address.FieldName, field.TypeString, value)
	}
	if value, ok := auo.mutation.AddressLine(); ok {
		_spec.SetField(address.FieldAddressLine, field.TypeString, value)
	}
	if value, ok := auo.mutation.Latitude(); ok {
		_spec.SetField(address.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := auo.mutation.AddedLatitude(); ok {
		_spec.AddField(address.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := auo.mutation.Longtitude(); ok {
		_spec.SetField(address.FieldLongtitude, field.TypeFloat64, value)
	}
	if value, ok := auo.mutation.AddedLongtitude(); ok {
		_spec.AddField(address.FieldLongtitude, field.TypeFloat64, value)
	}
	if value, ok := auo.mutation.Description(); ok {
		_spec.SetField(address.FieldDescription, field.TypeString, value)
	}
	if auo.mutation.AddressOwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.AddressOwnerTable,
			Columns: []string{address.AddressOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.AddressOwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.AddressOwnerTable,
			Columns: []string{address.AddressOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.AddressOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   address.AddressOrderTable,
			Columns: []string{address.AddressOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: order.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.AddressOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   address.AddressOrderTable,
			Columns: []string{address.AddressOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: order.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Address{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
