// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (a *Address) AddressMaster(ctx context.Context) (*User, error) {
	result, err := a.Edges.AddressMasterOrErr()
	if IsNotLoaded(err) {
		result, err = a.QueryAddressMaster().Only(ctx)
	}
	return result, err
}

func (u *User) AddressSlaves(ctx context.Context) (result []*Address, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = u.NamedAddressSlaves(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = u.Edges.AddressSlavesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = u.QueryAddressSlaves().All(ctx)
	}
	return result, err
}
