// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TheOguzhan/Drone-Mobile-App-Backend/ent/order"
	"github.com/TheOguzhan/Drone-Mobile-App-Backend/ent/warehouse"
	"github.com/google/uuid"
)

// WarehouseCreate is the builder for creating a Warehouse entity.
type WarehouseCreate struct {
	config
	mutation *WarehouseMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (wc *WarehouseCreate) SetName(s string) *WarehouseCreate {
	wc.mutation.SetName(s)
	return wc
}

// SetDescription sets the "description" field.
func (wc *WarehouseCreate) SetDescription(s string) *WarehouseCreate {
	wc.mutation.SetDescription(s)
	return wc
}

// SetAddressLine sets the "address_line" field.
func (wc *WarehouseCreate) SetAddressLine(s string) *WarehouseCreate {
	wc.mutation.SetAddressLine(s)
	return wc
}

// SetLatitude sets the "latitude" field.
func (wc *WarehouseCreate) SetLatitude(f float64) *WarehouseCreate {
	wc.mutation.SetLatitude(f)
	return wc
}

// SetLongtitude sets the "longtitude" field.
func (wc *WarehouseCreate) SetLongtitude(f float64) *WarehouseCreate {
	wc.mutation.SetLongtitude(f)
	return wc
}

// SetID sets the "id" field.
func (wc *WarehouseCreate) SetID(u uuid.UUID) *WarehouseCreate {
	wc.mutation.SetID(u)
	return wc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (wc *WarehouseCreate) SetNillableID(u *uuid.UUID) *WarehouseCreate {
	if u != nil {
		wc.SetID(*u)
	}
	return wc
}

// SetWarehouseOrderID sets the "warehouse_order" edge to the Order entity by ID.
func (wc *WarehouseCreate) SetWarehouseOrderID(id uuid.UUID) *WarehouseCreate {
	wc.mutation.SetWarehouseOrderID(id)
	return wc
}

// SetNillableWarehouseOrderID sets the "warehouse_order" edge to the Order entity by ID if the given value is not nil.
func (wc *WarehouseCreate) SetNillableWarehouseOrderID(id *uuid.UUID) *WarehouseCreate {
	if id != nil {
		wc = wc.SetWarehouseOrderID(*id)
	}
	return wc
}

// SetWarehouseOrder sets the "warehouse_order" edge to the Order entity.
func (wc *WarehouseCreate) SetWarehouseOrder(o *Order) *WarehouseCreate {
	return wc.SetWarehouseOrderID(o.ID)
}

// Mutation returns the WarehouseMutation object of the builder.
func (wc *WarehouseCreate) Mutation() *WarehouseMutation {
	return wc.mutation
}

// Save creates the Warehouse in the database.
func (wc *WarehouseCreate) Save(ctx context.Context) (*Warehouse, error) {
	wc.defaults()
	return withHooks[*Warehouse, WarehouseMutation](ctx, wc.sqlSave, wc.mutation, wc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wc *WarehouseCreate) SaveX(ctx context.Context) *Warehouse {
	v, err := wc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wc *WarehouseCreate) Exec(ctx context.Context) error {
	_, err := wc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wc *WarehouseCreate) ExecX(ctx context.Context) {
	if err := wc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wc *WarehouseCreate) defaults() {
	if _, ok := wc.mutation.ID(); !ok {
		v := warehouse.DefaultID()
		wc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wc *WarehouseCreate) check() error {
	if _, ok := wc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Warehouse.name"`)}
	}
	if _, ok := wc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Warehouse.description"`)}
	}
	if _, ok := wc.mutation.AddressLine(); !ok {
		return &ValidationError{Name: "address_line", err: errors.New(`ent: missing required field "Warehouse.address_line"`)}
	}
	if _, ok := wc.mutation.Latitude(); !ok {
		return &ValidationError{Name: "latitude", err: errors.New(`ent: missing required field "Warehouse.latitude"`)}
	}
	if _, ok := wc.mutation.Longtitude(); !ok {
		return &ValidationError{Name: "longtitude", err: errors.New(`ent: missing required field "Warehouse.longtitude"`)}
	}
	return nil
}

func (wc *WarehouseCreate) sqlSave(ctx context.Context) (*Warehouse, error) {
	if err := wc.check(); err != nil {
		return nil, err
	}
	_node, _spec := wc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	wc.mutation.id = &_node.ID
	wc.mutation.done = true
	return _node, nil
}

func (wc *WarehouseCreate) createSpec() (*Warehouse, *sqlgraph.CreateSpec) {
	var (
		_node = &Warehouse{config: wc.config}
		_spec = sqlgraph.NewCreateSpec(warehouse.Table, sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeUUID))
	)
	if id, ok := wc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := wc.mutation.Name(); ok {
		_spec.SetField(warehouse.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := wc.mutation.Description(); ok {
		_spec.SetField(warehouse.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := wc.mutation.AddressLine(); ok {
		_spec.SetField(warehouse.FieldAddressLine, field.TypeString, value)
		_node.AddressLine = value
	}
	if value, ok := wc.mutation.Latitude(); ok {
		_spec.SetField(warehouse.FieldLatitude, field.TypeFloat64, value)
		_node.Latitude = value
	}
	if value, ok := wc.mutation.Longtitude(); ok {
		_spec.SetField(warehouse.FieldLongtitude, field.TypeFloat64, value)
		_node.Longtitude = value
	}
	if nodes := wc.mutation.WarehouseOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   warehouse.WarehouseOrderTable,
			Columns: []string{warehouse.WarehouseOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: order.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WarehouseCreateBulk is the builder for creating many Warehouse entities in bulk.
type WarehouseCreateBulk struct {
	config
	builders []*WarehouseCreate
}

// Save creates the Warehouse entities in the database.
func (wcb *WarehouseCreateBulk) Save(ctx context.Context) ([]*Warehouse, error) {
	specs := make([]*sqlgraph.CreateSpec, len(wcb.builders))
	nodes := make([]*Warehouse, len(wcb.builders))
	mutators := make([]Mutator, len(wcb.builders))
	for i := range wcb.builders {
		func(i int, root context.Context) {
			builder := wcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WarehouseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wcb *WarehouseCreateBulk) SaveX(ctx context.Context) []*Warehouse {
	v, err := wcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wcb *WarehouseCreateBulk) Exec(ctx context.Context) error {
	_, err := wcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wcb *WarehouseCreateBulk) ExecX(ctx context.Context) {
	if err := wcb.Exec(ctx); err != nil {
		panic(err)
	}
}
