// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Address is the predicate function for address builders.
type Address func(*sql.Selector)

// Drone is the predicate function for drone builders.
type Drone func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Warehouse is the predicate function for warehouse builders.
type Warehouse func(*sql.Selector)
